apiVersion: apps/v1
kind: Deployment
metadata:
  name: week7-task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week7-task-service
  template:
    metadata:
      labels:
        app: week7-task-service
    spec:
      containers:
        - name: task-service
          image: week7-task-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: TASK_DATA_FILE
              value: /app/data/tasks.tsv
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: task-data
              mountPath: /app/data
      volumes:
        - name: task-data
          persistentVolumeClaim:
            claimName: week7-task-data
